name: correct_python
on:
  pull_request:
  push:
jobs:
  correct_python:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]    # [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, pypy3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - shell: python
        run: |
          import os, sys
          print(sys.version_info)
          print(os.environ)
