name: checkout_with_main_branch
on: [push, pull_request]
jobs:
  checkout_with_main_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: main
      - run: git branch || true
      - run: git diff main || true

