name: correct_python
on:
  pull_request:
  push:
jobs:
  correct_python:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]    # [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.9]  # [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, pypy3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - shell: python
        env:
          EXPECTED_PYTHON: ${{ matrix.python-version }}
        run: import os, sys ; assert sys.version.startswith(os.getenv("EXPECTED_PYTHON"))
          # import json, os, sys
          # print(sys.version_info)
          # d = dict(os.environ)
          # d.pop('GITHUB_ENV')
          # print(json.dumps(d, indent=2, sort_keys=True))
          # assert sys.version.startswith(os.getenv("EXPECTED_PYTHON"))
