# https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
name: postgres_on_postgres
on: [pull_request, push]
jobs:
  postgres_on_postgres:
    runs-on: ubuntu-latest
    container: postgres
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          # POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      #- run: apt update && apt install -y postgresql
      - run: psql --host=postgres -c 'create database infobase_test;'
        env:
          POSTGRES_PASSWORD: postgres
