# https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
name: postgres_on_postgres
on: [pull_request, push]
jobs:
  postgres_on_postgres:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: ubuntu:latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - run: apt update && apt install -y postgresql
      - run: psql --host=postgres -c 'create database infobase_test;'
        env:
          POSTGRES_PASSWORD: postgres
