# https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
name: postgres_service
on: [pull_request, push]
jobs:
  postgres_service:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - env:
          # The hostname used to communicate with the PostgreSQL service container
          # POSTGRES_HOST: postgres  # localhost
          # The default PostgreSQL port
          # POSTGRES_PORT: 5432
        run: psql --host=localhost --port=5432 --username=postgres -c 'create database infobase_test;'
