# https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
name: postgres_on_localhost
on: [pull_request, push]
jobs:
  postgres_on_localhost:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - run: ls /etc || true
      - run: cat /etc/hosts || true
      - run: sudo echo '127.0.0.1 postgres' >> /etc/hosts
      - run: cat /etc/hosts || true
      - run: psql --host=postgres --username=postgres -c 'create database infobase_test;'
