name: workflow_info
on: [push, pull_request]
jobs:
  workflow_info:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: |
          echo "GitHub: ${GITHUB_CONTEXT}"
          echo "Job: ${JOB_CONTEXT}"
          echo "Steps: ${STEPS_CONTEXT}"
          echo "Runner: ${RUNNER_CONTEXT}"
          echo "Straregy: ${STRATEGY_CONTEXT}"
          echo "Matrix: ${MATRIX_CONTEXT}"
      - shell: python
        run: |
          from os import environ
          from pprint import pprint
          pprint(environ)

  operating_system_info:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          # RUNNER_OS: ${{ runner.os }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: |
          echo "Runner: ${RUNNER_CONTEXT}"
          echo "Runner_OS: ${RUNNER_OS}"
          echo "Matrix: ${MATRIX_CONTEXT}"
      - shell: python
        run: |
          from os import environ
          from pprint import pprint
          pprint(environ)
      - if: runner.os == 'macOS'
        run: echo "We are on a Mac!"
        shell: bash
