name: workflow_info
on: [push, pull_request]
jobs:
  workflow_info:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: |
          echo "GitHub: ${GITHUB_CONTEXT}"
          echo "Job: ${JOB_CONTEXT}"
          echo "Steps: ${STEPS_CONTEXT}"
          echo "Runner: ${RUNNER_CONTEXT}"
          echo "Straregy: ${STRATEGY_CONTEXT}"
          echo "Matrix${MATRIX_CONTEXT}"
